#!/usr/bin/env bash
# SSH Phase Final：root 仅允许公钥登录，禁用密码登录；危险步骤必须二阶段确认。
set -Eeuo pipefail
PHASE_NAME="ssh-final"
source "${RRB_PROJECT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}/scripts/00-lib.sh"
require_root
load_config
require_supported_os

confirm_root_key="${CONFIRM_ROOT_KEY_LOGIN:-${CONFIRM_ADMIN_KEY_LOGIN:-}}"
[[ "$confirm_root_key" == "yes" ]] || die "拒绝执行最终 SSH 加固：请先另开窗口确认 root 可用 SSH key 登录，然后用 CONFIRM_ROOT_KEY_LOGIN=yes 重新执行。"

backup_path /etc/ssh/sshd_config
[[ -d /etc/ssh/sshd_config.d ]] && backup_path /etc/ssh/sshd_config.d
ensure_sshd_dropin_include


id root >/dev/null 2>&1 || die "root 用户不存在。"
root_home="$(getent passwd root | cut -d: -f6)"
[[ -s "$root_home/.ssh/authorized_keys" ]] || die "root 未安装 authorized_keys，不能禁用密码登录。"

ALLOWED_USERS="root"
if [[ "$ENABLE_SFTP_USER" == "true" ]]; then
  id "$SFTP_USER" >/dev/null 2>&1 || die "ENABLE_SFTP_USER=true 但用户不存在：$SFTP_USER"
  ALLOWED_USERS="$ALLOWED_USERS $SFTP_USER"
fi

write_hardening_file() {
  local kbd_directive="$1"
  write_sshd_policy <<EOF
# Managed by reality-relay-bootstrap final hardening.
# Do not edit this file directly; change config.env and rerun ssh-final.
PermitRootLogin prohibit-password
PubkeyAuthentication yes
PasswordAuthentication no
${kbd_directive}
AuthenticationMethods publickey
PermitEmptyPasswords no

AllowUsers ${ALLOWED_USERS}

MaxAuthTries 3
MaxSessions 2
LoginGraceTime 30

X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no
PermitUserEnvironment no

ClientAliveInterval 300
ClientAliveCountMax 2
EOF
}

write_hardening_file "KbdInteractiveAuthentication no"

if ! is_dry_run; then
  sshd="$(sshd_bin)"
  if ! "$sshd" -t >/tmp/reality-relay-bootstrap-sshd-test.err 2>&1; then
    if grep -qi 'KbdInteractiveAuthentication' /tmp/reality-relay-bootstrap-sshd-test.err; then
      warn "当前 OpenSSH 不支持 KbdInteractiveAuthentication，自动改用 ChallengeResponseAuthentication。"
      write_hardening_file "ChallengeResponseAuthentication no"
    else
      cat /tmp/reality-relay-bootstrap-sshd-test.err >&2
      die "sshd -t 未通过，已停止 reload。"
    fi
  fi
fi

if [[ "$ENABLE_SFTP_USER" == "true" ]]; then
  info "配置 SFTP-only 用户：$SFTP_USER。Match 块将放在 /etc/ssh/sshd_config 末尾。"
  if ! is_dry_run; then
    python3 - "$SFTP_USER" <<'PY'
import re
import sys
from pathlib import Path

user = sys.argv[1]
main = Path("/etc/ssh/sshd_config")
dropin_dir = Path("/etc/ssh/sshd_config.d")

files = [main]
if dropin_dir.is_dir():
    files.extend(sorted(dropin_dir.glob("*.conf")))

seen = False
subsystem_re = re.compile(r"^\s*Subsystem\s+sftp\s+", re.I)
for path in files:
    if not path.exists():
        continue
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    changed = False
    out = []
    for line in lines:
        if subsystem_re.match(line) and not line.lstrip().startswith("#"):
            if not seen:
                out.append("Subsystem sftp internal-sftp")
                seen = True
            else:
                out.append("# Disabled duplicate by reality-relay-bootstrap: " + line)
            changed = True
        else:
            out.append(line)
    if changed:
        path.write_text("\n".join(out) + "\n", encoding="utf-8")

if not seen:
    text = main.read_text(encoding="utf-8", errors="replace")
    if text and not text.endswith("\n"):
        text += "\n"
    text += "Subsystem sftp internal-sftp\n"
    main.write_text(text, encoding="utf-8")

start = f"# BEGIN reality-relay-bootstrap SFTP user {user}"
end = f"# END reality-relay-bootstrap SFTP user {user}"
text = main.read_text(encoding="utf-8", errors="replace")
legacy_pattern = re.compile(
    r"# BEGIN [A-Za-z0-9_-]+ SFTP user " + re.escape(user) +
    r".*?# END [A-Za-z0-9_-]+ SFTP user " + re.escape(user) + r"\n?",
    re.S,
)
text = legacy_pattern.sub("", text).rstrip() + "\n\n"
block = f"""{start}
Match User {user}
    ChrootDirectory /sftp/%u
    ForceCommand internal-sftp -d /upload -u 0027
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding no
    PermitTunnel no
{end}
"""
main.write_text(text + block, encoding="utf-8")
PY
  else
    log "DRY-RUN: normalize Subsystem sftp and append Match User $SFTP_USER to /etc/ssh/sshd_config"
  fi
fi

rm -f /tmp/reality-relay-bootstrap-sshd-test.err
test_sshd_config

info "检查最终 sshd -T 生效值。"
if ! is_dry_run; then
  sshd="$(sshd_bin)"
  if [[ "$RRB_VERBOSE" == "true" ]]; then
    "$sshd" -T -C "user=root,host=localhost,addr=127.0.0.1" \
      | grep -Ei '^(permitrootlogin|pubkeyauthentication|passwordauthentication|kbdinteractiveauthentication|challengeresponseauthentication|authenticationmethods|permitemptypasswords|allowusers|maxauthtries|x11forwarding|allowagentforwarding|allowtcpforwarding|permittunnel|gatewayports)\b' \
      | tee -a "$LOG_FILE"
  else
    "$sshd" -T -C "user=root,host=localhost,addr=127.0.0.1" \
      | grep -Ei '^(permitrootlogin|pubkeyauthentication|passwordauthentication|kbdinteractiveauthentication|challengeresponseauthentication|authenticationmethods|permitemptypasswords|allowusers|maxauthtries|x11forwarding|allowagentforwarding|allowtcpforwarding|permittunnel|gatewayports)\b' \
      >>"$LOG_FILE"
  fi
fi

if ! is_dry_run; then
  effective="$("$(sshd_bin)" -T -C "user=root,host=localhost,addr=127.0.0.1")"
  grep -Eqi '^permitrootlogin (prohibit-password|without-password)$' <<<"$effective" || die "PermitRootLogin prohibit-password 未生效（实际：$(awk '$1 == "permitrootlogin" { print $2 }' <<<"$effective")）；请检查匹配 root 的 Match 配置，停止 reload。"
  grep -qi '^pubkeyauthentication yes$' <<<"$effective" || die "PubkeyAuthentication yes 未生效（实际：$(awk '$1 == "pubkeyauthentication" { print $2 }' <<<"$effective")），停止 reload。"
  grep -qi '^passwordauthentication no$' <<<"$effective" || die "PasswordAuthentication no 未生效（实际：$(awk '$1 == "passwordauthentication" { print $2 }' <<<"$effective")），停止 reload。"
  allowusers_line="$(grep -i '^allowusers ' <<<"$effective" || true)"
  [[ " $allowusers_line " =~ [[:space:]]root[[:space:]] ]] || die "AllowUsers 未包含 root，停止 reload。"
fi

reload_ssh

cat <<EOF

SSH 最终加固已应用。请不要关闭当前窗口，立刻另开 PowerShell 测试：

$(if [[ -n "$(server_ipv4_hosts)" ]]; then
  printf 'IPv4:\n'
  for host in $(server_ipv4_hosts); do
    printf '  ssh -p %s -o PreferredAuthentications=publickey -o PasswordAuthentication=no root@%s\n' "$SSH_PORT" "$host"
    printf '  ssh -p %s -o PubkeyAuthentication=no -o PreferredAuthentications=password root@%s\n' "$SSH_PORT" "$host"
  done
  printf '\n'
fi)
$(if [[ -n "$(server_ipv6_hosts)" ]]; then
  printf '\nIPv6:\n'
  for host in $(server_ipv6_hosts); do
    printf '  ssh -p %s -o PreferredAuthentications=publickey -o PasswordAuthentication=no root@%s\n' "$SSH_PORT" "$host"
    printf '  ssh -p %s -o PubkeyAuthentication=no -o PreferredAuthentications=password root@%s\n' "$SSH_PORT" "$host"
  done
  printf '\n'
fi)

预期：
  1. root key 登录成功。
  2. root 密码登录失败。
EOF
