#!/usr/bin/env bash
# SSH Phase Final：禁 root、禁密码、只允许指定用户；危险步骤必须二阶段确认。
set -Eeuo pipefail
PHASE_NAME="ssh-final"
source "${OBS_PROJECT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)}/scripts/00-lib.sh"
require_root
load_config
require_supported_os

[[ "${CONFIRM_ADMIN_KEY_LOGIN:-}" == "yes" ]] || die "拒绝执行最终 SSH 加固：请先另开窗口确认 ${ADMIN_USER} 可用 SSH key 登录且 sudo 正常，然后用 CONFIRM_ADMIN_KEY_LOGIN=yes 重新执行。"

backup_path /etc/ssh/sshd_config
[[ -d /etc/ssh/sshd_config.d ]] && backup_path /etc/ssh/sshd_config.d
ensure_sshd_dropin_include

id "$ADMIN_USER" >/dev/null 2>&1 || die "管理用户不存在：$ADMIN_USER"
admin_home="$(getent passwd "$ADMIN_USER" | cut -d: -f6)"
[[ -s "$admin_home/.ssh/authorized_keys" ]] || die "$ADMIN_USER 未安装 authorized_keys，不能禁用密码登录。"

ALLOWED_USERS="$ADMIN_USER"
if [[ "$ENABLE_SFTP_USER" == "true" ]]; then
  id "$SFTP_USER" >/dev/null 2>&1 || die "ENABLE_SFTP_USER=true 但用户不存在：$SFTP_USER"
  ALLOWED_USERS="$ALLOWED_USERS $SFTP_USER"
fi

write_hardening_file() {
  local kbd_directive="$1"
  write_root_file /etc/ssh/sshd_config.d/00-our-server-bootstrap-hardening.conf 0644 <<EOF
# Managed by our-server-bootstrap final hardening.
# Do not edit this file directly; change config.env and rerun ssh-final.
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
${kbd_directive}
AuthenticationMethods publickey
PermitEmptyPasswords no

AllowUsers ${ALLOWED_USERS}

MaxAuthTries 3
MaxSessions 2
LoginGraceTime 30

X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no
PermitUserEnvironment no

ClientAliveInterval 300
ClientAliveCountMax 2
EOF
}

write_hardening_file "KbdInteractiveAuthentication no"

if ! is_dry_run; then
  sshd="$(sshd_bin)"
  if ! "$sshd" -t >/tmp/our-sshd-test.err 2>&1; then
    if grep -qi 'KbdInteractiveAuthentication' /tmp/our-sshd-test.err; then
      warn "当前 OpenSSH 不支持 KbdInteractiveAuthentication，自动改用 ChallengeResponseAuthentication。"
      write_hardening_file "ChallengeResponseAuthentication no"
    else
      cat /tmp/our-sshd-test.err >&2
      die "sshd -t 未通过，已停止 reload。"
    fi
  fi
fi

if [[ "$ENABLE_SFTP_USER" == "true" ]]; then
  info "配置 SFTP-only 用户：$SFTP_USER。Match 块将放在 /etc/ssh/sshd_config 末尾。"
  if ! is_dry_run; then
    python3 - "$SFTP_USER" <<'PY'
import re
import sys
from pathlib import Path

user = sys.argv[1]
main = Path("/etc/ssh/sshd_config")
dropin_dir = Path("/etc/ssh/sshd_config.d")

files = [main]
if dropin_dir.is_dir():
    files.extend(sorted(dropin_dir.glob("*.conf")))

seen = False
subsystem_re = re.compile(r"^\s*Subsystem\s+sftp\s+", re.I)
for path in files:
    if not path.exists():
        continue
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    changed = False
    out = []
    for line in lines:
        if subsystem_re.match(line) and not line.lstrip().startswith("#"):
            if not seen:
                out.append("Subsystem sftp internal-sftp")
                seen = True
            else:
                out.append("# Disabled duplicate by our-server-bootstrap: " + line)
            changed = True
        else:
            out.append(line)
    if changed:
        path.write_text("\n".join(out) + "\n", encoding="utf-8")

if not seen:
    text = main.read_text(encoding="utf-8", errors="replace")
    if text and not text.endswith("\n"):
        text += "\n"
    text += "Subsystem sftp internal-sftp\n"
    main.write_text(text, encoding="utf-8")

start = f"# BEGIN our-server-bootstrap SFTP user {user}"
end = f"# END our-server-bootstrap SFTP user {user}"
text = main.read_text(encoding="utf-8", errors="replace")
pattern = re.compile(re.escape(start) + r".*?" + re.escape(end) + r"\n?", re.S)
text = pattern.sub("", text).rstrip() + "\n\n"
block = f"""{start}
Match User {user}
    ChrootDirectory /sftp/%u
    ForceCommand internal-sftp -d /upload -u 0027
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
    AllowTcpForwarding no
    PermitTunnel no
{end}
"""
main.write_text(text + block, encoding="utf-8")
PY
  else
    log "DRY-RUN: normalize Subsystem sftp and append Match User $SFTP_USER to /etc/ssh/sshd_config"
  fi
fi

rm -f /tmp/our-sshd-test.err
test_sshd_config

info "最终 sshd -T 生效值："
if ! is_dry_run; then
  sshd="$(sshd_bin)"
  "$sshd" -T -C "user=${ADMIN_USER},host=localhost,addr=127.0.0.1" \
    | grep -Ei '^(permitrootlogin|pubkeyauthentication|passwordauthentication|kbdinteractiveauthentication|challengeresponseauthentication|authenticationmethods|permitemptypasswords|allowusers|maxauthtries|x11forwarding|allowagentforwarding|allowtcpforwarding|permittunnel|gatewayports)\b' \
    | tee -a "$LOG_FILE"
fi

if ! is_dry_run; then
  effective="$("$(sshd_bin)" -T -C "user=${ADMIN_USER},host=localhost,addr=127.0.0.1")"
  grep -qi '^permitrootlogin no$' <<<"$effective" || die "PermitRootLogin no 未生效，停止 reload。"
  grep -qi '^pubkeyauthentication yes$' <<<"$effective" || die "PubkeyAuthentication yes 未生效，停止 reload。"
  grep -qi '^passwordauthentication no$' <<<"$effective" || die "PasswordAuthentication no 未生效，停止 reload。"
  grep -qi "^allowusers .*\\b${ADMIN_USER}\\b" <<<"$effective" || die "AllowUsers 未包含 $ADMIN_USER，停止 reload。"
fi

if is_dry_run; then
  log "DRY-RUN: rm -f /etc/ssh/sshd_config.d/00-our-server-bootstrap-phase1.conf"
else
  rm -f /etc/ssh/sshd_config.d/00-our-server-bootstrap-phase1.conf
fi
reload_ssh

cat <<EOF

SSH 最终加固已应用。请不要关闭当前窗口，立刻另开 PowerShell 测试：

  ssh -p $SSH_PORT -o PreferredAuthentications=publickey -o PasswordAuthentication=no ${ADMIN_USER}@${SERVER_IP:-服务器IP}
  ssh -p $SSH_PORT root@${SERVER_IP:-服务器IP}
  ssh -p $SSH_PORT -o PubkeyAuthentication=no -o PreferredAuthentications=password ${ADMIN_USER}@${SERVER_IP:-服务器IP}

预期：
  1. ${ADMIN_USER} key 登录成功。
  2. root 登录失败。
  3. 密码登录失败。
EOF
